name: cPocket
description: A CryptoCurrency Wallet Flutter App.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.0+1z

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get: ^4.6.1
  get_storage:
  intl: 0.17.0
  connectivity: ^3.0.6
  fluttertoast: ^8.0.9
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.0
  google_fonts: ^2.3.1
  images_picker: ^1.2.10
  auto_size_text: ^3.0.0
  url_launcher: ^6.0.20
  grouped_list: ^4.2.0
  qr_flutter: ^4.0.0
  webview_flutter: ^3.0.1
  simple_html_css: ^3.0.1+1
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.13
  group_radio_button: ^1.2.0
  country_code_picker: ^2.0.2
  marquee: ^2.2.1
  dotted_line: ^3.1.0
  flutter_switch: ^0.3.2
  dio: ^4.0.4
  logger: ^1.1.0
  syncfusion_flutter_charts: ^19.4.55
  flutter_tags: ^1.0.0-nullsafety.1  # Do not update this package library
  flutter_launcher_icons: ^0.10.0
  change_app_package_name: ^1.1.0


## **** after setup your project you will get error on common_widget.dart file on the line 614
  #(It is 'flutter_tags' library issue)
  ## *To solve the issue, please follow below steps....
  # 1. (It is 'flutter_tags' library issue)
  # 2. click the the 'ItemTags' with (cmd pressing on macOS/Alt pressing on windows)
  # 3. comment 152 and 153 line like bellow-----
  #    // if (_dataListInherited!.list!.length < _dataListInherited!.itemCount!)
  #    // _dataListInherited!.list!.length = _dataListInherited!.itemCount!;
  #### it will show the warning press ok with clicking 'I want to edit this file anyway'.


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/imagel.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/trading_slider.html
    - assets/trading_slider_ios.html

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
